// SPDX-FileCopyrightText: 2025 Errant
// SPDX-FileCopyrightText: 2024 metalgearsloth
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers
// SPDX-FileCopyrightText: 2023 Vasilis
// SPDX-FileCopyrightText: 2024 Vasilis
// SPDX-FileCopyrightText: 2023 Miro Kavaliou
// SPDX-FileCopyrightText: 2022 wrexbe
// SPDX-FileCopyrightText: 2022 Leeroy
// SPDX-FileCopyrightText: 2022 mirrorcult
// SPDX-FileCopyrightText: 2021 Visne
// SPDX-License-Identifier: MIT

using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        [Dependency] private readonly IClientAdminManager _adminManager = default!;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Tabs.SetTabTitle(0, Loc.GetString("ui-options-tab-misc"));
            Tabs.SetTabTitle(1, Loc.GetString("ui-options-tab-graphics"));
            Tabs.SetTabTitle(2, Loc.GetString("ui-options-tab-controls"));
            Tabs.SetTabTitle(3, Loc.GetString("ui-options-tab-audio"));
            Tabs.SetTabTitle(4, Loc.GetString("ui-options-tab-accessibility"));
            Tabs.SetTabTitle(5, Loc.GetString("ui-options-tab-admin"));

            UpdateTabs();
        }

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            Tabs.SetTabVisible(5, isAdmin);

            GraphicsTab.Control.ReloadValues();
            MiscTab.Control.ReloadValues();
            AccessibilityTab.Control.ReloadValues();
            AudioTab.Control.ReloadValues();
            AdminOptionsTab.Control.ReloadValues();
        }
    }
}
