// SPDX-FileCopyrightText: 2022 Jezithyr
// SPDX-FileCopyrightText: 2022 mirrorcult
// SPDX-FileCopyrightText: 2021 ShadowCommander
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterObjectiveControl : BoxContainer
{
    public CharacterObjectiveControl()
    {
        RobustXamlLoader.Load(this);
    }
}
