// SPDX-FileCopyrightText: 2026 Fruitsalad
// SPDX-FileCopyrightText: 2025 Hannah Giovanna Dawson
// SPDX-FileCopyrightText: 2025 LordCarve
// SPDX-FileCopyrightText: 2024 Saphire Lattice
// SPDX-FileCopyrightText: 2024 goet
// SPDX-FileCopyrightText: 2024 Thomas
// SPDX-FileCopyrightText: 2024 KrasnoshchekovPavel
// SPDX-FileCopyrightText: 2024 TsjipTsjip
// SPDX-FileCopyrightText: 2023 Whisper
// SPDX-FileCopyrightText: 2024 Whisper
// SPDX-FileCopyrightText: 2024 Rainfey
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers
// SPDX-FileCopyrightText: 2024 Krunklehorn
// SPDX-FileCopyrightText: 2023 Artjom
// SPDX-FileCopyrightText: 2023 metalgearsloth
// SPDX-FileCopyrightText: 2023 MilenVolf
// SPDX-FileCopyrightText: 2023 DrSmugleaf
// SPDX-FileCopyrightText: 2023 Visne
// SPDX-FileCopyrightText: 2022 Rinkashikachi
// SPDX-FileCopyrightText: 2022 Leon Friedrich
// SPDX-FileCopyrightText: 2022 Kara
// SPDX-FileCopyrightText: 2022 Rane
// SPDX-FileCopyrightText: 2022 Fishfish458
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
    }
}
