// SPDX-FileCopyrightText: 2025 pathetic meowmeow
// SPDX-FileCopyrightText: 2022 mirrorcult
// SPDX-FileCopyrightText: 2021 Visne
// SPDX-License-Identifier: MIT

using Content.Shared.Cargo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoOrderRow : PanelContainer
    {
        public CargoOrderData? Order { get; set; }

        public CargoOrderRow()
        {
            RobustXamlLoader.Load(this);
        }

        public void SetApproveVisible(bool visible)
        {
            Approve.Visible = visible;

            if (visible)
                Cancel.AddStyleClass("OpenLeft");
            else
                Cancel.RemoveStyleClass("OpenLeft");
        }
    }
}
