// SPDX-FileCopyrightText: 2025 Brandon Li
// SPDX-FileCopyrightText: 2025 metalgearsloth
// SPDX-FileCopyrightText: 2022 wrexbe
// SPDX-FileCopyrightText: 2022 mirrorcult
// SPDX-FileCopyrightText: 2021 DrSmugleaf
// SPDX-FileCopyrightText: 2021 Pieter-Jan Briers
// SPDX-FileCopyrightText: 2021 Javier Guardia Fernández
// SPDX-License-Identifier: MIT

using Content.Client.SubFloor;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Sandbox.Windows;

[GenerateTypedNameReferences]
public sealed partial class SandboxWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = null!;

    public SandboxWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void Opened()
    {
        base.Opened();
        // Make sure state is up to date.
        ToggleSubfloorButton.Pressed = _entManager.System<SubFloorHideSystem>().ShowAll;
    }
}
