// SPDX-FileCopyrightText: 2025 Kyle Tyo
// SPDX-FileCopyrightText: 2022 mirrorcult
// SPDX-FileCopyrightText: 2021 Visne
// SPDX-FileCopyrightText: 2021 DrSmugleaf
// SPDX-FileCopyrightText: 2021 Pieter-Jan Briers
// SPDX-FileCopyrightText: 2021 Leo
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control
    {
        [Dependency] private readonly IClientConsoleHost _console = default!;

        public RoundTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            StartRound.OnPressed += _ => _console.ExecuteCommand("startround");
            EndRound.OnPressed += _ => _console.ExecuteCommand("endround");
            RestartRound.OnPressed += _ => _console.ExecuteCommand("restartround");
            RestartRoundNow.OnPressed += _ => _console.ExecuteCommand("restartroundnow");
        }
    }
}
